[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "diffusion-homework"
version = "0.2.0"
requires-python = ">=3.9"
dependencies = [
  "clean-fid>=0.1.35",
  "gdown>=5.2.0",
  "ipykernel>=6.31.0",
  "matplotlib>=3.9.4",
  "numpy>=2.0.2",
  "pydantic>=2.10.4",
  "PyYAML>=5.4.1",
  "torch>=2.8.0",
  "torchvision>=0.23.0",
]

[tool.setuptools]
packages = ["src"]